### ISSUE TITLE
Can't  login the vm_multi on rpi4? "udhcpc: sending discover"

### ISSUE THREAD

**Issue by Jerryy959** [tiiuae/tii_sel4_build#13]
Hi,
I successfully started VM_ multi on my rpi4, but I can't start the system completely and enter the login interface. The **udhcpc** command always outputs a message, blocking the startup again and again.

That is "udhcpc: sending discover", how can i skip the init of network.

![image](https://user-images.githubusercontent.com/48466606/173499058-19dfdb45-8869-43dc-a1b4-7de549a6c068.png)

**Comment by elmankku** [comment]
Hi @Comet959 

Modify following overlay files:
- https://github.com/tiiuae/camkes-vm-examples/blob/rpi4/apps/Arm/vm_multi/overlay_files/vm0_bridge_setup.sh
- https://github.com/tiiuae/camkes-vm-examples/blob/rpi4/apps/Arm/vm_multi/overlay_files/vm_client_net_setup.sh

On workspace, these files are located at `projects/vm-examples/apps/Arm/vm_multi/overlay_files/`

**Comment by Jerryy959** [comment]
Hi, @elmankku 
I have tested and it really helps me!!!  Thanks !  
It can be closed.
